'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MyAccount

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''NewT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewT As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''THistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THistory As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ASettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASettings As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''AStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AStatement As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''GBankAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBankAccount As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MALastNameTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MALastNameTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MAFirstNameTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAFirstNameTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MADateOfBirthTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MADateOfBirthTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MAIdCardTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAIdCardTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MAOwnerPinTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAOwnerPinTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MALocalityTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MALocalityTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MAAddressTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAAddressTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MAPhoneTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAPhoneTxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AccountOwnerSessionDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountOwnerSessionDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource1AccountIdSessionDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1AccountIdSessionDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OwnerSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerSelected As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OwnerSelecter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerSelecter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SelectedAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedAccount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AccountSelecter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountSelecter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MyAccountDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyAccountDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SettingsSaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettingsSaveButton As Global.System.Web.UI.WebControls.Button
End Class
