'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewTransaction

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''NewT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewT As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''THistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents THistory As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ASettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASettings As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''AStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AStatement As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''GBankAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBankAccount As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NTTransactionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTTransactionType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NTTransactionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTTransactionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NTExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTExplanation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NTCounterpart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTCounterpart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewTransactionDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewTransactionDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''InitTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InitTransaction As Global.System.Web.UI.WebControls.Button
End Class
